services:
  - type: web
    name: masar
    runtime: docker
    plan: free
    branch: testing
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: MASAR_MODEL_PATH
        value: models/congestion_xgb.pkl
      - key: TOMTOM_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false